#!url=https://raw.githubusercontent.com/Zifeiyu-0/Script/main/Shadowrocket/wyymusic.module
#!name=网易云会员歌曲解锁
#!desc=使用时需开启代理，关闭代理则失效

[Script]

# > 网易云解锁VIP
网易云 = type=http-request, pattern=^http[s]?:\/\/.+music.+(player\/url|playlist|entrance|\/eapi\/search\/).*$, script-path=https://raw.githubusercontent.com/Zifeiyu-0/Script/main/QX/wyymusic.js, timeout=60, script-update-interval=0

[MITM]

hostname = %APPEND% *.music.163.com 

